diary/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

    root 'welcome#index'
    resources "entries"

end

diary/app/models/entry.rb
class Entry < ActiveRecord::Base
end

diary/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

diary/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index
		@entries = Entry.all
	end
	def show
		@entry = Entry.find(params["id"])
	end
	def create
		entry_params = params["entry"].permit("title", "contents")
		entry = Entry.create(entry_params)
		redirect_to(entry_path(entry))
	end
	def edit
		@entry = Entry.find(params["id"])
	end
	def update
		entry_params = params["entry"].permit("title", "contents")
		entry = Entry.find(params["id"])
		entry.update(entry_params)
		redirect_to(entry_path(entry))
	end
end

diary/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@websites = [
				["http://railsgirls.com", "Rails Girls"],
				["https://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
				["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
		]
		@entries = Entry.all
	end
end

diary/app/helpers/application_helper.rb
module ApplicationHelper
end

diary/app/helpers/entries_helper.rb
module EntriesHelper
end

diary/app/helpers/welcome_helper.rb
module WelcomeHelper
end

diary/app/views/entries/edit.html.erb
<%= form_for(@entry) do |form| %>
<p><%= form.label("title") %></p>
<p><%= form.text_field("title") %></p>
<p><%= form.label("contents") %></p>
<p><%= form.text_area("contents") %></p>
<P><%= form.submit %></p>
<% end %>
<P><%= link_to("Back to this entry", entry_path(@entry)) %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>

diary/app/views/entries/index.html.erb
<% for entry in @entries %>
	<h2><%= link_to(entry.title, entry_path(entry)) %></h2>	
	<p><%= entry.contents %></p>
<% end %>

<%= link_to("New entry", new_entry_path) %>

diary/app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
<p><%= form.label("title") %></p>
<p><%= form.text_field("title") %></p>
<p><%= form.label("contents") %></p>
<p><%= form.text_area("contents") %></p>
<p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>

diary/app/views/entries/show.html.erb
<h2><%= link_to(@entry.title, entry_path(@entry)) %></h2>
<p><%= @entry.date %></p>
<p><%= @entry.contents %></p>
<p><%= link_to("Edit this entry", edit_entry_path(@entry)) %></p>

diary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

diary/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
		<div>
			<h1>My favorite websites</h1>
			<% for url, name in @websites %>
				<li><a href="<%= url %>"><%= name %></a></li>
				<% end %>
		</div>
		<img src="http://railsgirls.com/images/rg-warsaw.png" /> 
		<h1>My Diary</h1>
		<% for entry in @entries %>
			<h2><%=entry.title %></h2>
			<p><%=entry.date %></p>
			<p><%=entry.contents %></p>
			<% end %>
		
		